#ifndef SLYMAIL_PROGRAM_INFO_H
#define SLYMAIL_PROGRAM_INFO_H

#define PROGRAM_NAME    "SlyMail"
#define CONFIG_PROGRAM_NAME "SlyMail Configuration"
#define PROGRAM_VERSION "0.52"
#define PROGRAM_DATE    "2026-03-26"

#endif // SLYMAIL_PROGRAM_INFO_H
